name: Black Format Check

on:
  push:
    branches: ["main"]
    paths:
      - '**.py'

  pull_request:
    branches: ["main"]
    paths:
      - '**.py'

jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install black nbqa

      - name: Check Python file formatting
        run: |
          echo "🔍 Checking Python files..."
          black --check --diff . || (
            echo "❌ Black found formatting issues in Python files." && exit 1
          )
